CREATE TABLE `cicids2017_sample` (
  `Flow Duration` int DEFAULT NULL,
  `Total Fwd Packets` int DEFAULT NULL,
  `Total Backward Packets` int DEFAULT NULL,
  `Total Length of Fwd Packets` int DEFAULT NULL,
  `Total Length of Bwd Packets` int DEFAULT NULL,
  `Fwd Packet Length Max` int DEFAULT NULL,
  `Fwd Packet Length Min` int DEFAULT NULL,
  `Fwd Packet Length Mean` double DEFAULT NULL,
  `Fwd Packet Length Std` double DEFAULT NULL,
  `Bwd Packet Length Max` int DEFAULT NULL,
  `Bwd Packet Length Min` int DEFAULT NULL,
  `Bwd Packet Length Mean` double DEFAULT NULL,
  `Bwd Packet Length Std` double DEFAULT NULL,
  `Flow Bytes/s` text DEFAULT NULL,
  `Flow Packets/s` text DEFAULT NULL,
  `Flow IAT Mean` double DEFAULT NULL,
  `Flow IAT Std` double DEFAULT NULL,
  `Flow IAT Max` int DEFAULT NULL,
  `Flow IAT Min` int DEFAULT NULL,
  `Fwd IAT Total` int DEFAULT NULL,
  `Fwd IAT Mean` double DEFAULT NULL,
  `Fwd IAT Std` double DEFAULT NULL,
  `Fwd IAT Max` int DEFAULT NULL,
  `Fwd IAT Min` int DEFAULT NULL,
  `Bwd IAT Total` int DEFAULT NULL,
  `Bwd IAT Mean` double DEFAULT NULL,
  `Bwd IAT Std` double DEFAULT NULL,
  `Bwd IAT Max` int DEFAULT NULL,
  `Bwd IAT Min` int DEFAULT NULL,
  `Fwd PSH Flags` int DEFAULT NULL,
  `Bwd PSH Flags` int DEFAULT NULL,
  `Fwd URG Flags` int DEFAULT NULL,
  `Bwd URG Flags` int DEFAULT NULL,
  `Fwd Header Length` int DEFAULT NULL,
  `Bwd Header Length` int DEFAULT NULL,
  `Fwd Packets/s` double DEFAULT NULL,
  `Bwd Packets/s` double DEFAULT NULL,
  `Min Packet Length` int DEFAULT NULL,
  `Max Packet Length` int DEFAULT NULL,
  `Packet Length Mean` double DEFAULT NULL,
  `Packet Length Std` double DEFAULT NULL,
  `Packet Length Variance` double DEFAULT NULL,
  `FIN Flag Count` int DEFAULT NULL,
  `SYN Flag Count` int DEFAULT NULL,
  `RST Flag Count` int DEFAULT NULL,
  `PSH Flag Count` int DEFAULT NULL,
  `ACK Flag Count` int DEFAULT NULL,
  `URG Flag Count` int DEFAULT NULL,
  `CWE Flag Count` int DEFAULT NULL,
  `ECE Flag Count` int DEFAULT NULL,
  `Down/Up Ratio` int DEFAULT NULL,
  `Average Packet Size` double DEFAULT NULL,
  `Avg Fwd Segment Size` double DEFAULT NULL,
  `Avg Bwd Segment Size` double DEFAULT NULL,
  `Fwd Header Length.1` int DEFAULT NULL,
  `Fwd Avg Bytes/Bulk` int DEFAULT NULL,
  `Fwd Avg Packets/Bulk` int DEFAULT NULL,
  `Fwd Avg Bulk Rate` int DEFAULT NULL,
  `Bwd Avg Bytes/Bulk` int DEFAULT NULL,
  `Bwd Avg Packets/Bulk` int DEFAULT NULL,
  `Bwd Avg Bulk Rate` int DEFAULT NULL,
  `Subflow Fwd Packets` int DEFAULT NULL,
  `Subflow Fwd Bytes` int DEFAULT NULL,
  `Subflow Bwd Packets` int DEFAULT NULL,
  `Subflow Bwd Bytes` int DEFAULT NULL,
  `Init_Win_bytes_forward` int DEFAULT NULL,
  `Init_Win_bytes_backward` int DEFAULT NULL,
  `act_data_pkt_fwd` int DEFAULT NULL,
  `min_seg_size_forward` int DEFAULT NULL,
  `Active Mean` double DEFAULT NULL,
  `Active Std` double DEFAULT NULL,
  `Active Max` int DEFAULT NULL,
  `Active Min` int DEFAULT NULL,
  `Idle Mean` double DEFAULT NULL,
  `Idle Std` double DEFAULT NULL,
  `Idle Max` int DEFAULT NULL,
  `Idle Min` int DEFAULT NULL,
  `Label` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SHOW VARIABLES LIKE "secure_file_priv";
# Make sure secure_file_priv = ""

# Locate .csv file into the proper acessible folder
LOAD DATA INFILE '\CICIDS2017_sample.csv'
INTO TABLE cicids2017_sample
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES

